language: cpp
compiler:
  - clang
  - gcc

# Setup different environments to test
env:
  global:
    - LIBSTDC_VERSION=4.9
    - CLANG_VERSION=3.5

# # Handle git submodules yourself
# git:
#     submodules: false

# # Use sed to replace the SSH URL with the public URL, then initialize submodules
# before_install:
#     # Replace <user> and <token> with your GitHub username and access token respectively
#     - sed -i 's/git@github.com:/https:\/\/williammc:CM4MYiCv2R6MseDQ711j@github.com\//' .gitmodules
#     - git submodule update --init --recursive

# Setup repos etc before installation
before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - if [ "$CXX" == "clang++" ];  then echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list; fi
  - if [ "$CXX" == "clang++" ];  then echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main" | sudo tee -a /etc/apt/sources.list; fi
  - if [ "$CXX" == "clang++" ];  then echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list; fi
  - sudo apt-get update -qq

# Install dependencies
install:
  - sudo apt-get -qq install build-essential
  - sudo apt-get -qq --allow-unauthenticated install libstdc++-${LIBSTDC_VERSION}-dev
  - sudo apt-get -qq --allow-unauthenticated install clang-${CLANG_VERSION}

# command to run tests
script: 
  - clang++ --version
  - cmake ./
  - make
  - if [ "`echo $CXX`" == "g++" ]; then ctest -C debug; fi